version: "2"
services:

  backend:
    build: ./backend
    image: diffy-backend
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - DIFFY_DB_HOST=db
      - DIFFY_WEB_HOST=0.0.0.0
      - DIFFY_GA_ANALYTICS_KEY=none
    stop_signal: SIGINT

  frontend:
    build: ./frontend
    image: diffy-frontend
    ports:
      - 4200:4200
    stop_signal: SIGINT

  db:
    image: mongo:latest
    ports:
      - 27017:27017
